name: SporeModLoader

on: [push, pull_request]

jobs:
  msvc-build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86
      - name: Prepare Environment
        run: |
          $env:revision = git describe --tags --always
          echo "GIT_REVISION=$env:revision" >> $env:GITHUB_ENV
      - name: Build SporeModLoader (msvc)
        run: |
          msbuild "SporeModLoader" `
            /p:Configuration=Release `
            /p:Platform=Win32 `
            /m
      - name: Build SporeModManager (msvc)
        run: |
          msbuild "SporeModManager" `
            /p:Configuration=Release `
            /p:Platform=Win32 `
            /m
      - name: Package SporeModLoader (msvc)
        run: |
          New-Item -ItemType Directory -Force -Path bin\SporebinEP1
          New-Item -ItemType Directory -Force -Path bin\SporeModLoader\CoreLibs\
          New-Item -ItemType Directory -Force -Path bin\SporeModLoader\ModLibs
          New-Item -ItemType Directory -Force -Path bin\SporeModLoader\SporeModManager
          New-Item -ItemType File -Force -Path bin\SporeModLoader\ModLibs\.keep

          Copy "3rdParty\Spore-ModAPI\dll\Release\SporeModAPI.dll"          "bin\SporeModLoader\CoreLibs\SporeModAPI.dll"
          Copy "3rdParty\Spore-ModAPI-legacy\SporeModAPI-disk.dll"          "bin\SporeModLoader\CoreLibs\SporeModAPI-disk.dll"
          copy "3rdParty\Spore-ModAPI-legacy\SporeModAPI-steam_patched.dll" "bin\SporeModLoader\CoreLibs\SporeModAPI-steam_patched.dll"

          Copy "SporeModLoader\Bin\Release\dinput8.dll"          "bin\SporebinEP1\dinput8.dll"
          Copy "SporeModManager\Bin\Release\SporeModManager.exe" "bin\SporeModLoader\SporeModManager\SporeModManager.exe"
      - name: Upload SporeModLoader (msvc)
        uses: actions/upload-artifact@v4
        with:
          name: msvc-build-artifacts
          path: bin/*
  linux-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare Environment
        run: |
          echo "GIT_REVISION=$(git describe --tags --always)" >> $GITHUB_ENV
      - name: Build SporeModManager (Linux)
        run: |
          make SporeModManager -j$(nproc)
      - name: Upload SporeModLoader (Linux for msvc)
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifacts
          path: bin/*
  mingw-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Packages
        run: |
          sudo apt-get -y install gcc-mingw-w64-i686 g++-mingw-w64-i686
      - name: Prepare Environment
        run: |
          echo "GIT_REVISION=$(git describe --tags --always)" >> $GITHUB_ENV
      - name: Build SporeModLoader (mingw)
        run: |
          make SporeModLoader -j$(nproc)
  package-artifacts:
    runs-on: ubuntu-20.04
    needs: [ msvc-build, linux-build ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare Environment
        run: |
          echo "GIT_REVISION=$(git describe --tags --always)" >> $GITHUB_ENV
      - name: Download msvc-build-artifacts
        uses: actions/download-artifact@v4
        with:
          name: msvc-build-artifacts
          path: artifacts
      - name: Download linux-build-artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build-artifacts
          path: artifacts
      - name: Upload SporeModLoader
        uses: actions/upload-artifact@v4
        with:
          name: SporeModLoader-${{ env.GIT_REVISION }}
          path: artifacts/*
  msvc-test:
    runs-on: windows-2022
    needs: [ package-artifacts ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare Environment
        run: |
          $env:revision = git describe --tags --always
          echo "GIT_REVISION=$env:revision" >> $env:GITHUB_ENV
      - name: Download SporeModManager (msvc)
        uses: actions/download-artifact@v4
        with:
          name: SporeModLoader-${{ env.GIT_REVISION }}
          path: artifact
      - name: Test SporeModManager (msvc)
        run: |
          python3 ./SporeModManager/test.py ./artifact/SporeModLoader/SporeModManager/SporeModManager.exe
  linux-test:
    runs-on: ubuntu-20.04
    needs: [ package-artifacts ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare Environment
        run: |
          echo "GIT_REVISION=$(git describe --tags --always)" >> $GITHUB_ENV
      - name: Download SporeModManager (Linux)
        uses: actions/download-artifact@v4
        with:
          name: SporeModLoader-${{ env.GIT_REVISION }}
          path: artifact
      - name: Test SporeModManager (Linux)
        run: |
          chmod +x ./artifact/SporeModLoader/SporeModManager/SporeModManager
          python3 ./SporeModManager/test.py ./artifact/SporeModLoader/SporeModManager/SporeModManager

